spring:
  application:
    name: zuul-server
server:
  port: 8084
eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: feign-server
    api-b:
      path: /api-b/**
      serviceId: ribbon-consumer