eureka:
  instance:
    hostname: eureka2
  client:
    #fetch-registry: false
    #register-with-eureka: true
    service-url:
      defaultZone: http://eureka1:8761/eureka/
spring:
  application:
    name: eureka-server
server:
  port: 8762
  
