spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuboxiao0518/SpringcloudConfig/
          search-paths:
          - respo
          username: yuboxiao0518
          password: ybx2306062008
      label: master
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest

server:
  port: 8888
eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka/#,http://localhost:8762/eureka/



management:
  endpoints:
    web:
      exposure:
        include:
        - bus-refresh

